model:
  model_name: csp
  clip_model: "ViT-L/14"


train:
  experiment_name: csp_all_BCE
  dataset: multi_attrs_all
  split: multi_attr_split_all
  dataset_path: /root/autodl-tmp/data/CZSL/multi_attr 
  optimizer: Adam
  scheduler: None
  step_size: 5
  gamma: 0.5
  lr: 0.00005
  attr_dropout: 0.3
  weight_decay: 0.00001
  context_length: 8
  train_batch_size: 12
  gradient_accumulation_steps: 2
  seed: 0
  epochs: 40
  save_path: 
  val_metric: best_loss
  save_final_model: True
  multi_label_loss: BCE
  wandb: True

test:
  test_context_length: 16
  eval_batch_size: 64
  open_world: True
  topk: 1
  text_encoder_batch_size: 1024
  threshold_trials: 50
  bias: 0.001
  text_first: True